// This file has been automatically generated by capnp-es. 
import * as $ from "capnp-es";
export const _capnpFileId = BigInt("0xe3fca095c1cb2e87");
export class BigIntBag extends $.Struct {
  static readonly _capnp = {
    displayName: "BigIntBag",
    id: "86748469b18e4943",
    size: new $.ObjectSize(32, 0),
    defaultDefaultSigned: $.getInt64Mask(-BigInt("0xdb4da5f7ef412b1")),
    defaultDefaultUnsigned: $.getUint64Mask(BigInt("0xdb4da5f7ef412b1"))
  };
  getSigned(): bigint {
    return $.Struct.getInt64(0, this);
  }
  setSigned(value: bigint): void {
    $.Struct.setInt64(0, value, this);
  }
  getUnsigned(): bigint {
    return $.Struct.getUint64(8, this);
  }
  setUnsigned(value: bigint): void {
    $.Struct.setUint64(8, value, this);
  }
  getDefaultSigned(): bigint {
    return $.Struct.getInt64(16, this, BigIntBag._capnp.defaultDefaultSigned);
  }
  setDefaultSigned(value: bigint): void {
    $.Struct.setInt64(16, value, this, BigIntBag._capnp.defaultDefaultSigned);
  }
  getDefaultUnsigned(): bigint {
    return $.Struct.getUint64(24, this, BigIntBag._capnp.defaultDefaultUnsigned);
  }
  setDefaultUnsigned(value: bigint): void {
    $.Struct.setUint64(24, value, this, BigIntBag._capnp.defaultDefaultUnsigned);
  }
  toString(): string {
    return "BigIntBag_" + super.toString();
  }
}
