// This file has been automatically generated by capnp-es. 
import * as $ from "capnp-es";
export const _capnpFileId = BigInt("0xe0b7ff464fbc7ee2");
export class Foo extends $.Struct {
  static readonly _capnp = {
    displayName: "Foo",
    id: "ebf41ad8c4cd4576",
    size: new $.ObjectSize(0, 2)
  };
  getBar(): string {
    return $.Struct.getText(0, this);
  }
  setBar(value: string): void {
    $.Struct.setText(0, value, this);
  }
  getBaz(): string {
    return $.Struct.getText(1, this);
  }
  setBaz(value: string): void {
    $.Struct.setText(1, value, this);
  }
  toString(): string {
    return "Foo_" + super.toString();
  }
}
