// This file has been automatically generated by capnp-es. 
import * as $ from "capnp-es";
export const _capnpFileId = BigInt("0xe0b7ff464fbc7ee1");
export class Foo extends $.Struct {
  static readonly _capnp = {
    displayName: "Foo",
    id: "9e8e6186e9348688",
    size: new $.ObjectSize(0, 1)
  };
  get bar(): string {
    return $.Struct.getText(0, this);
  }
  set bar(value: string) {
    $.Struct.setText(0, value, this);
  }
  toString(): string {
    return "Foo_" + super.toString();
  }
}
