// This file has been automatically generated by capnp-es.
import * as $ from "capnp-es";
import { Baz } from "./import-bar.js";
export const _capnpFileId = BigInt("0xfc552bdafbb0b889");
export class Foo extends $.Struct {
  static readonly BAZ_CONST = $.readRawPointer(new Uint8Array([0x10, 0x02, 0x40, 0x01, 0x00, 0x00]).buffer);
  static readonly _capnp = {
    displayName: "Foo",
    id: "f92e265d07c50136",
    size: new $.ObjectSize(0, 1)
  };
  _adoptBaz(value: $.Orphan<Baz>): void {
    $.utils.adopt(value, $.utils.getPointer(0, this));
  }
  _disownBaz(): $.Orphan<Baz> {
    return $.utils.disown(this.baz);
  }
  get baz(): Baz {
    return $.utils.getStruct(0, Baz, this);
  }
  _hasBaz(): boolean {
    return !$.utils.isNull($.utils.getPointer(0, this));
  }
  _initBaz(): Baz {
    return $.utils.initStructAt(0, Baz, this);
  }
  set baz(value: Baz) {
    $.utils.copyFrom(value, $.utils.getPointer(0, this));
  }
  toString(): string {
    return "Foo_" + super.toString();
  }
}
