// This file has been automatically generated by capnp-es. 
import * as $ from "capnp-es";
import { Baz } from "./import-bar.js";
export const _capnpFileId = BigInt("0xfc552bdafbb0b889");
export class Foo extends $.Struct {
  static readonly BAZ_CONST = $.readRawPointer(new Uint8Array([0x10, 0x02, 0x40, 0x01, 0x00, 0x00]).buffer);
  static readonly _capnp = {
    displayName: "Foo",
    id: "f92e265d07c50136",
    size: new $.ObjectSize(0, 1)
  };
  adoptBaz(value: $.Orphan<Baz>): void {
    $.Struct.adopt(value, $.Struct.getPointer(0, this));
  }
  disownBaz(): $.Orphan<Baz> {
    return $.Struct.disown(this.getBaz());
  }
  getBaz(): Baz {
    return $.Struct.getStruct(0, Baz, this);
  }
  hasBaz(): boolean {
    return !$.Struct.isNull($.Struct.getPointer(0, this));
  }
  initBaz(): Baz {
    return $.Struct.initStructAt(0, Baz, this);
  }
  setBaz(value: Baz): void {
    $.Struct.copyFrom(value, $.Struct.getPointer(0, this));
  }
  toString(): string {
    return "Foo_" + super.toString();
  }
}
