// This file has been automatically generated by capnp-es. 
import * as $ from "capnp-es";
import { TestEnum, TestAllTypes, TestDefaults, TestAnyPointer, TestAnyOthers, TestOutOfOrder, TestUnion, TestUnnamedUnion, TestUnionInUnion, TestGroups, TestInterleavedGroups, TestUnionDefaults, TestNestedTypes, TestNestedTypes_NestedEnum, TestNestedTypes_NestedStruct, TestNestedTypes_NestedStruct_NestedEnum, TestUsing, TestLists, TestLists_Struct0, TestLists_Struct1, TestLists_Struct8, TestLists_Struct16, TestLists_Struct32, TestLists_Struct64, TestLists_StructP, TestLists_Struct0c, TestLists_Struct1c, TestLists_Struct8c, TestLists_Struct16c, TestLists_Struct32c, TestLists_Struct64c, TestLists_StructPc, TestFieldZeroIsBit, TestListDefaults, TestLateUnion, TestOldVersion, TestNewVersion, TestOldUnionVersion, TestNewUnionVersion, TestStructUnion, TestStructUnion_SomeStruct, TestPrintInlineStructs, TestPrintInlineStructs_InlineStruct, TestWholeFloatDefault, TestGenerics, TestGenerics_Inner, TestGenerics_Inner2, TestGenerics_Inner2_DeepNest, TestGenerics_UseAliases, TestGenericsWrapper, TestGenericsWrapper2, TestGenericsUnion, TestUseGenerics, TestEmptyStruct, TestConstants, TestAnyPointerConstants, TestPipeline_Box, TestPipeline_AnyBox, TestTailCallee_TailResult, TestMembrane_Result, TestContainMembrane, TestTransferCap, TestTransferCap_Element, TestSturdyRef, TestSturdyRefHostId, TestSturdyRefObjectId, TestSturdyRefObjectId_Tag, TestProvisionId, TestRecipientId, TestThirdPartyCapId, TestJoinResult, TestNameAnnotation, TestNameAnnotation_BadlyNamedEnum, TestNameAnnotation_NestedStruct, TestNameAnnotation_NestedStruct_DeeplyNestedEnum } from "./test.js";
export const _capnpFileId = BigInt("0xf36d7b330303c66e");
export class TestImport extends $.Struct {
  static readonly _capnp = {
    displayName: "TestImport",
    id: "bc55b08b672b5d97",
    size: new $.ObjectSize(8, 1)
  };
  adoptField(value: $.Orphan<TestAllTypes>): void {
    $.Struct.adopt(value, $.Struct.getPointer(0, this));
  }
  disownField(): $.Orphan<TestAllTypes> {
    return $.Struct.disown(this.field);
  }
  get field(): TestAllTypes {
    return $.Struct.getStruct(0, TestAllTypes, this);
  }
  hasField(): boolean {
    return !$.Struct.isNull($.Struct.getPointer(0, this));
  }
  initField(): TestAllTypes {
    return $.Struct.initStructAt(0, TestAllTypes, this);
  }
  set field(value: TestAllTypes) {
    $.Struct.copyFrom(value, $.Struct.getPointer(0, this));
  }
  get enumField(): TestEnum {
    return $.Struct.getUint16(0, this) as TestEnum;
  }
  set enumField(value: TestEnum) {
    $.Struct.setUint16(0, value, this);
  }
  toString(): string {
    return "TestImport_" + super.toString();
  }
}
