// This file has been automatically generated by capnp-es. 
import * as $ from "capnp-es";
import { Node, Node_Parameter, Node_NestedNode, Field, Enumerant, Superclass, Method, Type, Brand, Brand_Scope, Brand_Binding, Value, Annotation, ElementSize } from "capnp-es/capnp/schema";
import { TestImport } from "./test-import.js";
import { TestEnum, TestAllTypes, TestDefaults, TestAnyPointer, TestAnyOthers, TestOutOfOrder, TestUnion, TestUnnamedUnion, TestUnionInUnion, TestGroups, TestInterleavedGroups, TestUnionDefaults, TestNestedTypes, TestNestedTypes_NestedEnum, TestNestedTypes_NestedStruct, TestNestedTypes_NestedStruct_NestedEnum, TestUsing, TestLists, TestLists_Struct0, TestLists_Struct1, TestLists_Struct8, TestLists_Struct16, TestLists_Struct32, TestLists_Struct64, TestLists_StructP, TestLists_Struct0c, TestLists_Struct1c, TestLists_Struct8c, TestLists_Struct16c, TestLists_Struct32c, TestLists_Struct64c, TestLists_StructPc, TestFieldZeroIsBit, TestListDefaults, TestLateUnion, TestOldVersion, TestNewVersion, TestOldUnionVersion, TestNewUnionVersion, TestStructUnion, TestStructUnion_SomeStruct, TestPrintInlineStructs, TestPrintInlineStructs_InlineStruct, TestWholeFloatDefault, TestGenerics, TestGenerics_Inner, TestGenerics_Inner2, TestGenerics_Inner2_DeepNest, TestGenerics_UseAliases, TestGenericsWrapper, TestGenericsWrapper2, TestGenericsUnion, TestUseGenerics, TestEmptyStruct, TestConstants, TestAnyPointerConstants, TestPipeline_Box, TestPipeline_AnyBox, TestTailCallee_TailResult, TestMembrane_Result, TestContainMembrane, TestTransferCap, TestTransferCap_Element, TestSturdyRef, TestSturdyRefHostId, TestSturdyRefObjectId, TestSturdyRefObjectId_Tag, TestProvisionId, TestRecipientId, TestThirdPartyCapId, TestJoinResult, TestNameAnnotation, TestNameAnnotation_BadlyNamedEnum, TestNameAnnotation_NestedStruct, TestNameAnnotation_NestedStruct_DeeplyNestedEnum } from "./test.js";
export const _capnpFileId = BigInt("0xc64a3bf0338a124a");
export class TestImport2 extends $.Struct {
  static readonly _capnp = {
    displayName: "TestImport2",
    id: "f6bd77f100ecb0ff",
    size: new $.ObjectSize(8, 7)
  };
  adoptFoo(value: $.Orphan<TestAllTypes>): void {
    $.Struct.adopt(value, $.Struct.getPointer(0, this));
  }
  disownFoo(): $.Orphan<TestAllTypes> {
    return $.Struct.disown(this.foo);
  }
  get foo(): TestAllTypes {
    return $.Struct.getStruct(0, TestAllTypes, this);
  }
  hasFoo(): boolean {
    return !$.Struct.isNull($.Struct.getPointer(0, this));
  }
  initFoo(): TestAllTypes {
    return $.Struct.initStructAt(0, TestAllTypes, this);
  }
  set foo(value: TestAllTypes) {
    $.Struct.copyFrom(value, $.Struct.getPointer(0, this));
  }
  adoptBar(value: $.Orphan<Node>): void {
    $.Struct.adopt(value, $.Struct.getPointer(1, this));
  }
  disownBar(): $.Orphan<Node> {
    return $.Struct.disown(this.bar);
  }
  get bar(): Node {
    return $.Struct.getStruct(1, Node, this);
  }
  hasBar(): boolean {
    return !$.Struct.isNull($.Struct.getPointer(1, this));
  }
  initBar(): Node {
    return $.Struct.initStructAt(1, Node, this);
  }
  set bar(value: Node) {
    $.Struct.copyFrom(value, $.Struct.getPointer(1, this));
  }
  adoptBaz(value: $.Orphan<TestImport>): void {
    $.Struct.adopt(value, $.Struct.getPointer(2, this));
  }
  disownBaz(): $.Orphan<TestImport> {
    return $.Struct.disown(this.baz);
  }
  get baz(): TestImport {
    return $.Struct.getStruct(2, TestImport, this);
  }
  hasBaz(): boolean {
    return !$.Struct.isNull($.Struct.getPointer(2, this));
  }
  initBaz(): TestImport {
    return $.Struct.initStructAt(2, TestImport, this);
  }
  set baz(value: TestImport) {
    $.Struct.copyFrom(value, $.Struct.getPointer(2, this));
  }
  adoptBox(value: $.Orphan<Node_Parameter>): void {
    $.Struct.adopt(value, $.Struct.getPointer(3, this));
  }
  disownBox(): $.Orphan<Node_Parameter> {
    return $.Struct.disown(this.box);
  }
  get box(): Node_Parameter {
    return $.Struct.getStruct(3, Node_Parameter, this);
  }
  hasBox(): boolean {
    return !$.Struct.isNull($.Struct.getPointer(3, this));
  }
  initBox(): Node_Parameter {
    return $.Struct.initStructAt(3, Node_Parameter, this);
  }
  set box(value: Node_Parameter) {
    $.Struct.copyFrom(value, $.Struct.getPointer(3, this));
  }
  adoptBee(value: $.Orphan<Node_NestedNode>): void {
    $.Struct.adopt(value, $.Struct.getPointer(4, this));
  }
  disownBee(): $.Orphan<Node_NestedNode> {
    return $.Struct.disown(this.bee);
  }
  get bee(): Node_NestedNode {
    return $.Struct.getStruct(4, Node_NestedNode, this);
  }
  hasBee(): boolean {
    return !$.Struct.isNull($.Struct.getPointer(4, this));
  }
  initBee(): Node_NestedNode {
    return $.Struct.initStructAt(4, Node_NestedNode, this);
  }
  set bee(value: Node_NestedNode) {
    $.Struct.copyFrom(value, $.Struct.getPointer(4, this));
  }
  adoptBok(value: $.Orphan<Brand_Scope>): void {
    $.Struct.adopt(value, $.Struct.getPointer(5, this));
  }
  disownBok(): $.Orphan<Brand_Scope> {
    return $.Struct.disown(this.bok);
  }
  get bok(): Brand_Scope {
    return $.Struct.getStruct(5, Brand_Scope, this);
  }
  hasBok(): boolean {
    return !$.Struct.isNull($.Struct.getPointer(5, this));
  }
  initBok(): Brand_Scope {
    return $.Struct.initStructAt(5, Brand_Scope, this);
  }
  set bok(value: Brand_Scope) {
    $.Struct.copyFrom(value, $.Struct.getPointer(5, this));
  }
  adoptBip(value: $.Orphan<Brand_Binding>): void {
    $.Struct.adopt(value, $.Struct.getPointer(6, this));
  }
  disownBip(): $.Orphan<Brand_Binding> {
    return $.Struct.disown(this.bip);
  }
  get bip(): Brand_Binding {
    return $.Struct.getStruct(6, Brand_Binding, this);
  }
  hasBip(): boolean {
    return !$.Struct.isNull($.Struct.getPointer(6, this));
  }
  initBip(): Brand_Binding {
    return $.Struct.initStructAt(6, Brand_Binding, this);
  }
  set bip(value: Brand_Binding) {
    $.Struct.copyFrom(value, $.Struct.getPointer(6, this));
  }
  get bep(): ElementSize {
    return $.Struct.getUint16(0, this) as ElementSize;
  }
  set bep(value: ElementSize) {
    $.Struct.setUint16(0, value, this);
  }
  toString(): string {
    return "TestImport2_" + super.toString();
  }
}
