// This file has been automatically generated by capnp-es. 
import * as $ from "capnp-es";
export const _capnpFileId = BigInt("0xc81a48fa54bfdd1e");
export class Upgrade extends $.Struct {
  static readonly _capnp = {
    displayName: "Upgrade",
    id: "b274c862a78a049c",
    size: new $.ObjectSize(8, 3)
  };
  static _SelfReferences: $.ListCtor<Upgrade>;
  get legacyName(): string {
    return $.Struct.getText(0, this);
  }
  set legacyName(value: string) {
    $.Struct.setText(0, value, this);
  }
  get legacyId(): number {
    return $.Struct.getInt32(0, this);
  }
  set legacyId(value: number) {
    $.Struct.setInt32(0, value, this);
  }
  adoptSelfReference(value: $.Orphan<Upgrade>): void {
    $.Struct.adopt(value, $.Struct.getPointer(1, this));
  }
  disownSelfReference(): $.Orphan<Upgrade> {
    return $.Struct.disown(this.selfReference);
  }
  get selfReference(): Upgrade {
    return $.Struct.getStruct(1, Upgrade, this);
  }
  hasSelfReference(): boolean {
    return !$.Struct.isNull($.Struct.getPointer(1, this));
  }
  initSelfReference(): Upgrade {
    return $.Struct.initStructAt(1, Upgrade, this);
  }
  set selfReference(value: Upgrade) {
    $.Struct.copyFrom(value, $.Struct.getPointer(1, this));
  }
  adoptSelfReferences(value: $.Orphan<$.List<Upgrade>>): void {
    $.Struct.adopt(value, $.Struct.getPointer(2, this));
  }
  disownSelfReferences(): $.Orphan<$.List<Upgrade>> {
    return $.Struct.disown(this.selfReferences);
  }
  get selfReferences(): $.List<Upgrade> {
    return $.Struct.getList(2, Upgrade._SelfReferences, this);
  }
  hasSelfReferences(): boolean {
    return !$.Struct.isNull($.Struct.getPointer(2, this));
  }
  initSelfReferences(length: number): $.List<Upgrade> {
    return $.Struct.initList(2, Upgrade._SelfReferences, length, this);
  }
  set selfReferences(value: $.List<Upgrade>) {
    $.Struct.copyFrom(value, $.Struct.getPointer(2, this));
  }
  toString(): string {
    return "Upgrade_" + super.toString();
  }
}
Upgrade._SelfReferences = $.CompositeList(Upgrade);
