// This file has been automatically generated by capnp-es.
import * as $ from "capnp-es";
export const _capnpFileId = BigInt("0xc81a48fa54bfdd1e");
export class Upgrade extends $.Struct {
  static readonly _capnp = {
    displayName: "Upgrade",
    id: "b274c862a78a049c",
    size: new $.ObjectSize(8, 3)
  };
  static _SelfReferences: $.ListCtor<Upgrade>;
  get legacyName(): string {
    return $.utils.getText(0, this);
  }
  set legacyName(value: string) {
    $.utils.setText(0, value, this);
  }
  get legacyId(): number {
    return $.utils.getInt32(0, this);
  }
  set legacyId(value: number) {
    $.utils.setInt32(0, value, this);
  }
  _adoptSelfReference(value: $.Orphan<Upgrade>): void {
    $.utils.adopt(value, $.utils.getPointer(1, this));
  }
  _disownSelfReference(): $.Orphan<Upgrade> {
    return $.utils.disown(this.selfReference);
  }
  get selfReference(): Upgrade {
    return $.utils.getStruct(1, Upgrade, this);
  }
  _hasSelfReference(): boolean {
    return !$.utils.isNull($.utils.getPointer(1, this));
  }
  _initSelfReference(): Upgrade {
    return $.utils.initStructAt(1, Upgrade, this);
  }
  set selfReference(value: Upgrade) {
    $.utils.copyFrom(value, $.utils.getPointer(1, this));
  }
  _adoptSelfReferences(value: $.Orphan<$.List<Upgrade>>): void {
    $.utils.adopt(value, $.utils.getPointer(2, this));
  }
  _disownSelfReferences(): $.Orphan<$.List<Upgrade>> {
    return $.utils.disown(this.selfReferences);
  }
  get selfReferences(): $.List<Upgrade> {
    return $.utils.getList(2, Upgrade._SelfReferences, this);
  }
  _hasSelfReferences(): boolean {
    return !$.utils.isNull($.utils.getPointer(2, this));
  }
  _initSelfReferences(length: number): $.List<Upgrade> {
    return $.utils.initList(2, Upgrade._SelfReferences, length, this);
  }
  set selfReferences(value: $.List<Upgrade>) {
    $.utils.copyFrom(value, $.utils.getPointer(2, this));
  }
  toString(): string {
    return "Upgrade_" + super.toString();
  }
}
Upgrade._SelfReferences = $.CompositeList(Upgrade);
