// This file has been automatically generated by capnp-es. 
import * as $ from "capnp-es";
export const _capnpFileId = BigInt("0xef1b5abe02e1f8d4");
export const Person_PhoneNumber_Type = {
  MOBILE: 0,
  HOME: 1,
  WORK: 2
} as const;
export type Person_PhoneNumber_Type = (typeof Person_PhoneNumber_Type)[keyof typeof Person_PhoneNumber_Type];
export class Person_PhoneNumber extends $.Struct {
  static readonly Type = Person_PhoneNumber_Type;
  static readonly _capnp = {
    displayName: "PhoneNumber",
    id: "af663da31c027e0e",
    size: new $.ObjectSize(8, 1)
  };
  getNumber(): string {
    return $.Struct.getText(0, this);
  }
  setNumber(value: string): void {
    $.Struct.setText(0, value, this);
  }
  getType(): Person_PhoneNumber_Type {
    return $.Struct.getUint16(0, this) as Person_PhoneNumber_Type;
  }
  setType(value: Person_PhoneNumber_Type): void {
    $.Struct.setUint16(0, value, this);
  }
  toString(): string {
    return "Person_PhoneNumber_" + super.toString();
  }
}
export const Person_Employment_Which = {
  UNEMPLOYED: 0,
  EMPLOYER: 1,
  SCHOOL: 2,
  SELF_EMPLOYED: 3
} as const;
export type Person_Employment_Which = (typeof Person_Employment_Which)[keyof typeof Person_Employment_Which];
export class Person_Employment extends $.Struct {
  static readonly UNEMPLOYED = Person_Employment_Which.UNEMPLOYED;
  static readonly EMPLOYER = Person_Employment_Which.EMPLOYER;
  static readonly SCHOOL = Person_Employment_Which.SCHOOL;
  static readonly SELF_EMPLOYED = Person_Employment_Which.SELF_EMPLOYED;
  static readonly _capnp = {
    displayName: "employment",
    id: "e88780a90af3da0c",
    size: new $.ObjectSize(8, 4)
  };
  isUnemployed(): boolean {
    return $.Struct.getUint16(4, this) === 0;
  }
  setUnemployed(): void {
    $.Struct.setUint16(4, 0, this);
  }
  getEmployer(): string {
    $.Struct.testWhich("employer", $.Struct.getUint16(4, this), 1, this);
    return $.Struct.getText(3, this);
  }
  isEmployer(): boolean {
    return $.Struct.getUint16(4, this) === 1;
  }
  setEmployer(value: string): void {
    $.Struct.setUint16(4, 1, this);
    $.Struct.setText(3, value, this);
  }
  getSchool(): string {
    $.Struct.testWhich("school", $.Struct.getUint16(4, this), 2, this);
    return $.Struct.getText(3, this);
  }
  isSchool(): boolean {
    return $.Struct.getUint16(4, this) === 2;
  }
  setSchool(value: string): void {
    $.Struct.setUint16(4, 2, this);
    $.Struct.setText(3, value, this);
  }
  isSelfEmployed(): boolean {
    return $.Struct.getUint16(4, this) === 3;
  }
  setSelfEmployed(): void {
    $.Struct.setUint16(4, 3, this);
  }
  toString(): string {
    return "Person_Employment_" + super.toString();
  }
  which(): Person_Employment_Which {
    return $.Struct.getUint16(4, this) as Person_Employment_Which;
  }
}
export class Person extends $.Struct {
  static readonly PhoneNumber = Person_PhoneNumber;
  static readonly _capnp = {
    displayName: "Person",
    id: "d94307c4985be8e7",
    size: new $.ObjectSize(8, 4)
  };
  static _Phones: $.ListCtor<Person_PhoneNumber>;
  getId(): number {
    return $.Struct.getUint32(0, this);
  }
  setId(value: number): void {
    $.Struct.setUint32(0, value, this);
  }
  getName(): string {
    return $.Struct.getText(0, this);
  }
  setName(value: string): void {
    $.Struct.setText(0, value, this);
  }
  getEmail(): string {
    return $.Struct.getText(1, this);
  }
  setEmail(value: string): void {
    $.Struct.setText(1, value, this);
  }
  adoptPhones(value: $.Orphan<$.List<Person_PhoneNumber>>): void {
    $.Struct.adopt(value, $.Struct.getPointer(2, this));
  }
  disownPhones(): $.Orphan<$.List<Person_PhoneNumber>> {
    return $.Struct.disown(this.getPhones());
  }
  getPhones(): $.List<Person_PhoneNumber> {
    return $.Struct.getList(2, Person._Phones, this);
  }
  hasPhones(): boolean {
    return !$.Struct.isNull($.Struct.getPointer(2, this));
  }
  initPhones(length: number): $.List<Person_PhoneNumber> {
    return $.Struct.initList(2, Person._Phones, length, this);
  }
  setPhones(value: $.List<Person_PhoneNumber>): void {
    $.Struct.copyFrom(value, $.Struct.getPointer(2, this));
  }
  getEmployment(): Person_Employment {
    return $.Struct.getAs(Person_Employment, this);
  }
  initEmployment(): Person_Employment {
    return $.Struct.getAs(Person_Employment, this);
  }
  toString(): string {
    return "Person_" + super.toString();
  }
}
export class AddressBook extends $.Struct {
  static readonly _capnp = {
    displayName: "AddressBook",
    id: "c06ea6d038a357bb",
    size: new $.ObjectSize(0, 1)
  };
  static _People: $.ListCtor<Person>;
  adoptPeople(value: $.Orphan<$.List<Person>>): void {
    $.Struct.adopt(value, $.Struct.getPointer(0, this));
  }
  disownPeople(): $.Orphan<$.List<Person>> {
    return $.Struct.disown(this.getPeople());
  }
  getPeople(): $.List<Person> {
    return $.Struct.getList(0, AddressBook._People, this);
  }
  hasPeople(): boolean {
    return !$.Struct.isNull($.Struct.getPointer(0, this));
  }
  initPeople(length: number): $.List<Person> {
    return $.Struct.initList(0, AddressBook._People, length, this);
  }
  setPeople(value: $.List<Person>): void {
    $.Struct.copyFrom(value, $.Struct.getPointer(0, this));
  }
  toString(): string {
    return "AddressBook_" + super.toString();
  }
}
Person._Phones = $.CompositeList(Person_PhoneNumber);
AddressBook._People = $.CompositeList(Person);
