// This file has been automatically generated by capnp-es.
import * as capnp from "capnp-es";
export const _capnpFileId = BigInt("0xef1b5abe02e1f8d4");
export const Person_PhoneNumber_Type = {
  MOBILE: 0,
  HOME: 1,
  WORK: 2
};
export class Person_PhoneNumber extends capnp.Struct {
  static Type = Person_PhoneNumber_Type;
  static _capnp = {
    displayName: "PhoneNumber",
    id: "af663da31c027e0e",
    size: new capnp.ObjectSize(8, 1)
  };
  getNumber() {
    return capnp.Struct.getText(0, this);
  }
  setNumber(value) {
    capnp.Struct.setText(0, value, this);
  }
  getType() {
    return capnp.Struct.getUint16(0, this);
  }
  setType(value) {
    capnp.Struct.setUint16(0, value, this);
  }
  toString() {
    return "Person_PhoneNumber_" + super.toString();
  }
}
export const Person_Employment_Which = {
  UNEMPLOYED: 0,
  EMPLOYER: 1,
  SCHOOL: 2,
  SELF_EMPLOYED: 3
};
export class Person_Employment extends capnp.Struct {
  static UNEMPLOYED = Person_Employment_Which.UNEMPLOYED;
  static EMPLOYER = Person_Employment_Which.EMPLOYER;
  static SCHOOL = Person_Employment_Which.SCHOOL;
  static SELF_EMPLOYED = Person_Employment_Which.SELF_EMPLOYED;
  static _capnp = {
    displayName: "employment",
    id: "e88780a90af3da0c",
    size: new capnp.ObjectSize(8, 4)
  };
  isUnemployed() {
    return capnp.Struct.getUint16(4, this) === 0;
  }
  setUnemployed() {
    capnp.Struct.setUint16(4, 0, this);
  }
  getEmployer() {
    capnp.Struct.testWhich("employer", capnp.Struct.getUint16(4, this), 1, this);
    return capnp.Struct.getText(3, this);
  }
  isEmployer() {
    return capnp.Struct.getUint16(4, this) === 1;
  }
  setEmployer(value) {
    capnp.Struct.setUint16(4, 1, this);
    capnp.Struct.setText(3, value, this);
  }
  getSchool() {
    capnp.Struct.testWhich("school", capnp.Struct.getUint16(4, this), 2, this);
    return capnp.Struct.getText(3, this);
  }
  isSchool() {
    return capnp.Struct.getUint16(4, this) === 2;
  }
  setSchool(value) {
    capnp.Struct.setUint16(4, 2, this);
    capnp.Struct.setText(3, value, this);
  }
  isSelfEmployed() {
    return capnp.Struct.getUint16(4, this) === 3;
  }
  setSelfEmployed() {
    capnp.Struct.setUint16(4, 3, this);
  }
  toString() {
    return "Person_Employment_" + super.toString();
  }
  which() {
    return capnp.Struct.getUint16(4, this);
  }
}
export class Person extends capnp.Struct {
  static PhoneNumber = Person_PhoneNumber;
  static _capnp = {
    displayName: "Person",
    id: "d94307c4985be8e7",
    size: new capnp.ObjectSize(8, 4)
  };
  static _Phones;
  getId() {
    return capnp.Struct.getUint32(0, this);
  }
  setId(value) {
    capnp.Struct.setUint32(0, value, this);
  }
  getName() {
    return capnp.Struct.getText(0, this);
  }
  setName(value) {
    capnp.Struct.setText(0, value, this);
  }
  getEmail() {
    return capnp.Struct.getText(1, this);
  }
  setEmail(value) {
    capnp.Struct.setText(1, value, this);
  }
  adoptPhones(value) {
    capnp.Struct.adopt(value, capnp.Struct.getPointer(2, this));
  }
  disownPhones() {
    return capnp.Struct.disown(this.getPhones());
  }
  getPhones() {
    return capnp.Struct.getList(2, Person._Phones, this);
  }
  hasPhones() {
    return !capnp.Struct.isNull(capnp.Struct.getPointer(2, this));
  }
  initPhones(length) {
    return capnp.Struct.initList(2, Person._Phones, length, this);
  }
  setPhones(value) {
    capnp.Struct.copyFrom(value, capnp.Struct.getPointer(2, this));
  }
  getEmployment() {
    return capnp.Struct.getAs(Person_Employment, this);
  }
  initEmployment() {
    return capnp.Struct.getAs(Person_Employment, this);
  }
  toString() {
    return "Person_" + super.toString();
  }
}
export class AddressBook extends capnp.Struct {
  static _capnp = {
    displayName: "AddressBook",
    id: "c06ea6d038a357bb",
    size: new capnp.ObjectSize(0, 1)
  };
  static _People;
  adoptPeople(value) {
    capnp.Struct.adopt(value, capnp.Struct.getPointer(0, this));
  }
  disownPeople() {
    return capnp.Struct.disown(this.getPeople());
  }
  getPeople() {
    return capnp.Struct.getList(0, AddressBook._People, this);
  }
  hasPeople() {
    return !capnp.Struct.isNull(capnp.Struct.getPointer(0, this));
  }
  initPeople(length) {
    return capnp.Struct.initList(0, AddressBook._People, length, this);
  }
  setPeople(value) {
    capnp.Struct.copyFrom(value, capnp.Struct.getPointer(0, this));
  }
  toString() {
    return "AddressBook_" + super.toString();
  }
}
Person._Phones = capnp.CompositeList(Person_PhoneNumber);
AddressBook._People = capnp.CompositeList(Person);
